import { pool } from './database.js'
import readline from 'readline/promises'
import { stdin as input, stdout as output } from 'process'

const rl = readline.createInterface( { input, output });

const ask = async(question) => {
    const answer = await rl.question(question)
    return answer
}

const createDatabaseTables = async () => {
    const createTablesQuery = `
        CREATE TABLE IF NOT EXISTS "users" (
            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "first_name" VARCHAR(255) NOT NULL,
            "last_name" VARCHAR(255) NOT NULL,
            "email" VARCHAR(255) NOT NULL,
            "password_hash" VARCHAR(255) NOT NULL,
            "role_id" INTEGER NOT NULL,
            PRIMARY KEY("id")
        );




        CREATE TABLE IF NOT EXISTS "boards" (
            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "name" VARCHAR(255) DEFAULT 'Untitled',
            "description" TEXT,
            "owner_id" INTEGER,
            "project_id" INTEGER NOT NULL,
            PRIMARY KEY("id")
        );




        CREATE TABLE IF NOT EXISTS "roles" (
            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "name" VARCHAR(255) NOT NULL DEFAULT 'user',
            PRIMARY KEY("id")
        );




        CREATE TABLE IF NOT EXISTS "tasks" (
            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "name" VARCHAR(255),
            "description" TEXT,
            "created_at" TIMESTAMPTZ NOT NULL,
            "board_id" INTEGER NOT NULL,
            "assignee_id" INTEGER,
            "status_id" INTEGER NOT NULL,
            PRIMARY KEY("id")
        );




        CREATE TABLE IF NOT EXISTS "categories" (
            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "name" VARCHAR(255) NOT NULL,
            "description" TEXT,
            PRIMARY KEY("id")
        );




        CREATE TABLE IF NOT EXISTS "task_categories" (
            "task_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "category_id" INTEGER NOT NULL,
            PRIMARY KEY("task_id", "category_id")
        );




        CREATE TABLE IF NOT EXISTS "statuses" (
            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "name" VARCHAR(255) NOT NULL,
            PRIMARY KEY("id")
        );




        CREATE TABLE IF NOT EXISTS "task_history" (
            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "task_id" INTEGER NOT NULL,
            "status_id" INTEGER NOT NULL,
            "assignee_id" INTEGER,
            "change_date" TIMESTAMPTZ NOT NULL,
            PRIMARY KEY("id")
        );




        CREATE TABLE IF NOT EXISTS "projects" (
            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "name" VARCHAR(255),
            "description" TEXT,
            "owner_id" INTEGER,
            PRIMARY KEY("id")
        );




        CREATE TABLE IF NOT EXISTS "permissions" (
            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "name" VARCHAR(255),
            "description" TEXT,
            PRIMARY KEY("id")
        );




        CREATE TABLE IF NOT EXISTS "role_permissions" (
            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "role_id" INTEGER,
            "permission_id" INTEGER,
            PRIMARY KEY("id")
        );
    `

    try {
        const res = await pool.query(createTablesQuery)
        console.log('🎉 tables created successfully')
    } catch (err) {
        console.error('⚠️ error creating tables', err)
    }
}

const seedDatabase = async () => {
    const seedDatabaseQuery = `
    INSERT INTO roles (name) VALUES
        ('admin'),
        ('manager'),
        ('user');
    
    INSERT INTO users (first_name, last_name, email, password_hash, role_id) VALUES
        ('Alice', 'Smith', 'alice@example.com', 'test123', 1),  -- admin
        ('Bob', 'Johnson', 'bob@example.com', 'test123', 2),    -- manager
        ('Charlie', 'Lee', 'charlie@example.com', 'test123', 3); -- user

    INSERT INTO permissions (name, description) VALUES
        ('create_task', 'Can create tasks'),
        ('edit_task', 'Can edit tasks'),
        ('delete_task', 'Can delete tasks'),
        ('assign_task', 'Can assign tasks');

    INSERT INTO role_permissions (role_id, permission_id) VALUES
        (1, 1), -- admin: create_task
        (1, 2), -- admin: edit_task
        (1, 3), -- admin: delete_task
        (1, 4), -- admin: assign_task
        (2, 1), -- manager: create_task
        (2, 2), -- manager: edit_task
        (2, 4), -- manager: assign_task
        (3, 1); -- user: create_task

    INSERT INTO projects (name, description, owner_id) VALUES
        ('Website Redesign', 'Redesign the corporate website', 2),
        ('Mobile App', 'Develop the new mobile app', 1);

    INSERT INTO boards (name, description, project_id, owner_id) VALUES
        ('UI Design', 'Design tasks', 1, 2),
        ('Backend', 'Backend implementation tasks', 1, 2),
        ('iOS App', 'iOS development tasks', 2, 1),
        ('Android App', 'Android development tasks', 2, 1);

    INSERT INTO statuses (name) VALUES
        ('Back Log'),
        ('In Progress'),
        ('Review'),
        ('Complete');

    INSERT INTO tasks (name, description, created_at, board_id, assignee_id, status_id) VALUES
        ('Create wireframes', 'Wireframes for homepage', NOW(), 1, 3, 1),
        ('Setup backend DB', 'Configure PostgreSQL', NOW(), 2, 2, 2),
        ('Login screen', 'Implement login screen', NOW(), 3, 3, 1),
        ('Push notifications', 'Add push notifications', NOW(), 4, 3, 1);

    INSERT INTO categories (name, description) VALUES
        ('Design', 'Tasks related to design'),
        ('Development', 'Tasks related to coding'),
        ('Testing', 'Tasks for QA/testing');

    INSERT INTO task_categories (task_id, category_id) VALUES
        (1, 1), -- Create wireframes → Design
        (2, 2), -- Setup backend DB → Development
        (3, 2), -- Login screen → Development
        (4, 2); -- Push notifications → Development

    INSERT INTO task_history (task_id, status_id, assignee_id, change_date) VALUES
        (1, 1, 3, NOW()),
        (2, 2, 2, NOW()),
        (3, 1, 3, NOW()),
        (4, 1, 3, NOW());

    `
    try {
        const res = await pool.query(seedDatabaseQuery)
        console.log('🎉 tables seeded successfully')
    } catch (err) {
        console.error('⚠️ error seeding tables', err)
    }
    
}

const addForeignKeys = async () => {
    const addForeignKeysQuery = `
        ALTER TABLE "boards"
        ADD FOREIGN KEY("owner_id") REFERENCES "users"("id")
        ON UPDATE NO ACTION ON DELETE SET NULL;

        ALTER TABLE "users"
        ADD FOREIGN KEY("role_id") REFERENCES "roles"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

        ALTER TABLE "tasks"
        ADD FOREIGN KEY("board_id") REFERENCES "boards"("id")
        ON UPDATE NO ACTION ON DELETE CASCADE;

        ALTER TABLE "tasks"
        ADD FOREIGN KEY("assignee_id") REFERENCES "users"("id")
        ON UPDATE NO ACTION ON DELETE SET NULL;

        ALTER TABLE "task_categories"
        ADD FOREIGN KEY("category_id") REFERENCES "categories"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

        ALTER TABLE "task_categories"
        ADD FOREIGN KEY("task_id") REFERENCES "tasks"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

        ALTER TABLE "tasks"
        ADD FOREIGN KEY("status_id") REFERENCES "statuses"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

        ALTER TABLE "task_history"
        ADD FOREIGN KEY("task_id") REFERENCES "tasks"("id")
        ON UPDATE NO ACTION ON DELETE CASCADE;

        ALTER TABLE "task_history"
        ADD FOREIGN KEY("status_id") REFERENCES "statuses"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

        ALTER TABLE "task_history"
        ADD FOREIGN KEY("assignee_id") REFERENCES "users"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

        ALTER TABLE "projects"
        ADD FOREIGN KEY("owner_id") REFERENCES "users"("id")
        ON UPDATE NO ACTION ON DELETE SET NULL;

        ALTER TABLE "boards"
        ADD FOREIGN KEY("project_id") REFERENCES "projects"("id")
        ON UPDATE NO ACTION ON DELETE CASCADE;

        ALTER TABLE "role_permissions"
        ADD FOREIGN KEY("role_id") REFERENCES "roles"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

        ALTER TABLE "role_permissions"
        ADD FOREIGN KEY("permission_id") REFERENCES "permissions"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
    `

    try {
        const res = await pool.query(addForeignKeysQuery)
        console.log('🎉 foreign keys added successfully')
    } catch (err) {
        console.error('⚠️ error adding foreign keys', err)
    }
}
const resetDatabase = async () => {
    const confirm = await ask('⚠️ Are you sure you want to reset the database? (y/n) ')
    if (confirm.toLowerCase() !== 'y') {
        console.log('Reset aborted.');
        rl.close();
        return;
    }
    // Drop all tables by reverse dependency
    await pool.query(`DROP TABLE IF EXISTS
        task_history,
        task_categories,
        tasks,
        boards,
        projects,
        role_permissions,
        users,
        roles,
        categories,
        statuses,
        permissions
    ;`)
        .then(() => console.log('🎉 tables dropped successfully'))
        .catch(err => console.error('⚠️ error dropping tables', err))

    await createDatabaseTables();

    const confirmSeed = await ask('Do you want to seed the database with data? (y/n) ')
    if (confirmSeed.toLowerCase() === 'y') {
        await seedDatabase();
    }
    rl.close();

    await addForeignKeys();

    await pool.end();
    
}

resetDatabase()